version: '3.8'

services:
  puddle:
    build:
      context: .
      dockerfile: Dockerfile
    image: puddle:test
    container_name: puddle
    ports:
      - "5500:5500"
    restart: always
    depends_on:
      - db
    develop:
      watch:
        - path: ./requirements.txt
          action: rebuild
        - path: ./
          target: /app
          action: sync
  
  db:
    image: postgres
    container_name: db
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: puddle_db
    restart: always 
    volumes:
      - db_data:/var/lib/postgresql/data


volumes:
  db_data: